apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
        - name: phonebook-app
          image: pradyumn5/nodejs-phonebook:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/phonebook"